#Python Try Except
#Exception Handling

try:
    print(x)
except:
    print("An exception occurred.")     
